server.port: 8100

spring:
  application.name: payment-service
  data.mongodb:
    uri: mongodb://d_easy_user:123qwe@localhost:27017/d_easy_db?replicaSet=rs0

order-service-client:
#  host: http://localhost:8000
  uri: /find/{id}
  connection-timeout: 2000
  read-timeout: 10000

kafka:
  sender:
    bootstrap-servers: ${kafka.receiver.bootstrap-servers}
  topics:
    success-payed-orders-topic:
      name: success-payed-orders-topic

eureka:
  instance.preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka