
server.port: 8000

spring:
  application.name: order-service
  data.mongodb:
    uri: mongodb://d_easy_user:123qwe@localhost:27017/d_easy_db?replicaSet=rs0
    num-retries: 5
    first-backoff: 10
    max-backoff: 1000

kafka:
  receiver:
    bootstrap-servers: localhost:9092
    group-id: checked-orders-order-service-group
  sender:
    bootstrap-servers: ${kafka.receiver.bootstrap-servers}
  topics:
    new-orders-topic:
      name: new-orders-topic
      partitions: 1
      replicas: 1
    checked-addresses-topic:
      name: checked-addresses-topic
      partitions: 1
      replicas: 1
    checked-couriers-topic:
      name: checked-couriers-topic
      partitions: 1
      replicas: 1
    checked-menu-orders-topic:
      name: checked-menu-orders-topic
      partitions: 1
      replicas: 1
    checke-order-success-topic:
      name: checke-order-success-topic
      partitions: 1
      replicas: 1

#eureka:
#  instance.preferIpAddress: true
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://discovery-service:8761/eureka
