
server.port: 8000

spring:
  application.name: order-service
  data.mongodb:
      host: localhost:27017
      database: order-db
      username: order-user
      password: order-password

kafka:
  receiver:
    bootstrap-servers: localhost:9092
    group-id: checked-addresses-group
    auto-offset-reset: earliest
  sender:
    bootstrap-servers: ${kafka.receiver.bootstrap-servers}
  topics:
    in-progress-orders-topic:
      name: in-progress-orders-topic
      partitions: 1
      replicas: 1
    checked-addresses-topic:
      name: checked-addresses-topic
      partitions: 1
      replicas: 1
    checked-couriers-topic:
      name: checked-couriers-topic
      partitions: 1
      replicas: 1
    checked-menu-orders-topic:
      name: checked-menu-orders-topic
      partitions: 1
      replicas: 1

#eureka:
#  instance.preferIpAddress: true
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://discovery-service:8761/eureka
