
server.port: 8000

spring:
  application.name: order-service
  data.mongodb:
      host: mongo-container
      database: order-db
      username: order-user
      password: order-password

eureka:
  instance.preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka
