server.port: 8080

spring:
  application.name: courier-service
  data.mongodb:
    uri: mongodb://d_easy_user:123qwe@localhost:27017/d_easy_db?replicaSet=rs0

kafka:
  receiver:
    bootstrap-servers: localhost:9092
    group-id: new-orders-courier-service-group
    auto-offset-reset: earliest
  sender:
    bootstrap-servers: ${kafka.receiver.bootstrap-servers}
  topics:
    new-orders-topic:
      name: new-orders-topic
      partitions: 1
      replicas: 1
    checked-couriers-topic:
      name: checked-couriers-topic
      partitions: 1
      replicas: 1

#eureka:
#  instance.preferIpAddress: true
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://discovery-service:8761/eureka
