server.port: 8020

spring:
  application.name: address-service

kafka:
  receiver:
    bootstrap-servers: localhost:9092
    group-id: new-orders-address-service-group
    auto-offset-reset: earliest
  sender:
    bootstrap-servers: ${kafka.receiver.bootstrap-servers}
  topics:
    new-orders-topic:
      enabled: true
      name: new-orders-topic
      partitions: 1
      replicas: 1
    checked-addresses-topic:
      name: checked-addresses-topic
      partitions: 1
      replicas: 1

hazelcast:
  cache:
    etl-cache-name: address-check-result-cache
    map-name: address-check-result-map
    time-to-live: 360
    max-idle-seconds: 180

management:
  health:
    hazelcast:
      enabled: false

#eureka:
#  instance.preferIpAddress: true
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://discovery-service:8761/eureka
