server.port: 8020

spring:
  application.name: address-service
  data.mongodb:
    uri: mongodb://d_easy_user:123qwe@localhost:27017/d_easy_db?replicaSet=rs0

kafka:
  receiver:
    bootstrap-servers: localhost:9092
    group-id: new-orders-address-service-group
    auto-offset-reset: earliest
  sender:
    bootstrap-servers: ${kafka.receiver.bootstrap-servers}
  topics:
    new-orders-topic:
      name: new-orders-topic
    checked-addresses-topic:
      name: checked-addresses-topic

management:
  health:
    hazelcast:
      enabled: false

#eureka:
#  instance.preferIpAddress: true
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://discovery-service:8761/eureka
